"""Build the ordered LPython kernel translation unit from source fragments."""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
PARTS = ROOT / "kernel" / "parts"
ORDER = (
    "00_platform.inc.py",
    "10_storage.inc.py",
    "20_state_menu.inc.py",
    "30_game_render.inc.py",
    "40_entry.inc.py",
)


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("usage: gen_kernel_source.py OUTPUT")
    output = Path(sys.argv[1])
    chunks = ["# Generated from kernel/parts; do not edit this file.\n"]
    for name in ORDER:
        chunks.append(f"\n# --- {name} ---\n")
        chunks.append((PARTS / name).read_text(encoding="utf-8"))
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("".join(chunks), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()